In [2]:
import numpy as np

pose = [0,56, 0.34, -0.12, 0, 0, 0]
gripper = 0.87

eef_state = np.concatenate([pose, [gripper]])
print(eef_state)



[ 0.   56.    0.34 -0.12  0.    0.    0.    0.87]


In [4]:
joints = np.random.randint(0, 180_000, 6)
print(joints)
joints = np.deg2rad(joints / 1000)
print(joints)

[ 13334 159572  94338  67856 168445 156355]
[0.2327222  2.78505679 1.64650871 1.18431062 2.93991986 2.72890955]


In [9]:
def eef_conversion_inv(pose):
    """
    Convert piper data(0.001mm and 0.001degree) to data suited policy(meter and radian)
    """
    # 将前三位从0.001毫米转换为米
    pose[:3] = [p / 1_000_000 for p in pose[:3]]
    # 将后三位从角度转换为弧度
    pose[3:6] = [np.deg2rad(p / 1000) for p in pose[3:6]]

    # TODO: 夹爪单位转换还未实现

    return np.asarray(pose)

# eef = [54868, 0, 260369, 0, 84929, 0]
eef = np.asarray([54868, 0, 260369, 0, 84929, 0], dtype=np.float64)
eef_ = eef_conversion_inv(eef)
print(np.asarray(eef_))

[0.054868   0.         0.260369   0.         1.48229068 0.        ]


In [13]:
import pyrealsense2 as rs

context = rs.context()
devices = context.query_devices()
print(devices)
serial_number = [devices[i].get_info(rs.camera_info.serial_number) for i in range(len(devices))]
print(serial_number)

['427622273753']


In [22]:
import hid
import time

vendor_id = 0x256f
product_id = 0xc652

device = hid.device()
device.open(vendor_id, product_id)
while True:
    data = device.read(13)
    print(data)
    time.sleep(1)



[23, 44, 0]
[3, 1, 0]
[3, 0, 0]
[3, 1, 0]
[3, 0, 0]
[3, 1, 0]
[1, 2, 0, 23, 0, 223, 0, 246, 255, 91, 0, 0, 0]
[1, 234, 255, 0, 0, 130, 0, 217, 255, 248, 255, 162, 254]
[1, 238, 255, 0, 0, 188, 0, 0, 0, 244, 255, 162, 254]
[1, 239, 255, 0, 0, 188, 0, 0, 0, 244, 255, 162, 254]
[1, 210, 255, 12, 0, 148, 0, 254, 255, 241, 255, 162, 254]
[1, 200, 255, 29, 0, 169, 0, 0, 0, 219, 255, 175, 254]
[1, 210, 255, 23, 0, 170, 0, 0, 0, 214, 255, 169, 254]
[1, 157, 255, 30, 0, 116, 0, 249, 255, 241, 255, 208, 254]


KeyboardInterrupt: 

In [26]:
import pyrealsense2 as rs

cntext = rs.context()
devices = context.query_devices()
serial_number = [device.get_info(rs.camera_info.serial_number) for device in devices]
print(serial_number)

['427622273753', '001622071252']
